USE master;
GO

IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'Graphdb')
BEGIN
    ALTER DATABASE Graphdb SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE Graphdb;
END
GO

CREATE DATABASE Graphdb;
GO

USE Graphdb;
GO


CREATE TABLE ACTORS 
(TABNUM INT NOT NULL,
ACTNAME NVARCHAR(100),
AGE INT) AS NODE

CREATE TABLE FILMS
(FILMNUM INT NOT NULL,
FILMNAME NVARCHAR(100),
FYEAR INT) AS NODE

CREATE TABLE CREATORS
(REGNUM INT NOT NULL,
CREATNAME NVARCHAR(100),
AGE INT) AS NODE

INSERT INTO ACTORS (TABNUM, ACTNAME, AGE)
VALUES
(1, N'Leonardo DiCaprio', 47),
(2, N'Marlon Brando', 80),
(3, N'Samuel L. Jackson', 74),
(4, N'Christian Bale', 49),
(5, N'Tom Hanks', 67),
(6, N'Keanu Reeves', 59),
(7, N'Brad Pitt', 60),
(8, N'Morgan Freeman', 86),
(9, N'Elijah Wood', 43),
(10, N'Matthew McConaughey', 54);
INSERT INTO FILMS (FILMNUM, FILMNAME, FYEAR)
VALUES
(1, 'Inception', 2010),
(2, 'The Godfather', 1972),
(3, 'Pulp Fiction', 1994),
(4, 'The Dark Knight', 2008),
(5, 'Forrest Gump', 1994),
(6, 'The Matrix', 1999),
(7, 'Fight Club', 1999),
(8, 'The Shawshank Redemption', 1994),
(9, 'The Lord of the Rings: The Return of the King', 2003),
(10,  'Interstellar', 2014);
INSERT INTO CREATORS (REGNUM, CREATNAME, AGE)
VALUES
(1, N'Christopher Nolan', 53),
(2, N'Francis Ford Coppola', 85),
(3, N'Quentin Tarantino', 61),
(4, N'Steven Spielberg', 77),
(5, N'Martin Scorsese', 81),
(6, N'James Cameron', 69),
(7, N'Peter Jackson', 62),
(8, N'Ridley Scott', 86),
(9, N'Guillermo del Toro', 59),
(10, N'Sofia Coppola', 52);

CREATE TABLE actorInFilm AS EDGE
INSERT INTO actorInFilm 
VALUES 
((SELECT $node_id FROM ACTORS WHERE TABNUM = 1), (SELECT $node_id FROM FILMS WHERE FILMNUM = 2)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 1), (SELECT $node_id FROM FILMS WHERE FILMNUM = 3)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 1), (SELECT $node_id FROM FILMS WHERE FILMNUM = 4)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 2), (SELECT $node_id FROM FILMS WHERE FILMNUM = 5)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 3), (SELECT $node_id FROM FILMS WHERE FILMNUM = 2)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 5), (SELECT $node_id FROM FILMS WHERE FILMNUM = 6)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 8), (SELECT $node_id FROM FILMS WHERE FILMNUM = 3)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 9), (SELECT $node_id FROM FILMS WHERE FILMNUM = 4)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 2), (SELECT $node_id FROM FILMS WHERE FILMNUM = 7)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 8), (SELECT $node_id FROM FILMS WHERE FILMNUM = 5)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 10), (SELECT $node_id FROM FILMS WHERE FILMNUM = 10)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 7), (SELECT $node_id FROM FILMS WHERE FILMNUM = 8)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 3), (SELECT $node_id FROM FILMS WHERE FILMNUM = 1));
CREATE TABLE filmByCreator AS EDGE
INSERT INTO filmByCreator  
VALUES 
((SELECT $node_id FROM FILMS WHERE FILMNUM = 1), (SELECT $node_id FROM CREATORS WHERE REGNUM = 2)),
((SELECT $node_id FROM FILMS WHERE FILMNUM = 1), (SELECT $node_id FROM CREATORS WHERE REGNUM = 3)),
((SELECT $node_id FROM FILMS WHERE FILMNUM = 1), (SELECT $node_id FROM CREATORS WHERE REGNUM = 4)),
((SELECT $node_id FROM FILMS WHERE FILMNUM = 2), (SELECT $node_id FROM CREATORS WHERE REGNUM = 5)),
((SELECT $node_id FROM FILMS WHERE FILMNUM = 3), (SELECT $node_id FROM CREATORS WHERE REGNUM = 2)),
((SELECT $node_id FROM FILMS WHERE FILMNUM = 5), (SELECT $node_id FROM CREATORS WHERE REGNUM = 6)),
((SELECT $node_id FROM FILMS WHERE FILMNUM = 8), (SELECT $node_id FROM CREATORS WHERE REGNUM = 3)),
((SELECT $node_id FROM FILMS WHERE FILMNUM = 9), (SELECT $node_id FROM CREATORS WHERE REGNUM = 4)),
((SELECT $node_id FROM FILMS WHERE FILMNUM = 2), (SELECT $node_id FROM CREATORS WHERE REGNUM = 7)),
((SELECT $node_id FROM FILMS WHERE FILMNUM = 8), (SELECT $node_id FROM CREATORS WHERE REGNUM = 5)),
((SELECT $node_id FROM FILMS WHERE FILMNUM = 10), (SELECT $node_id FROM CREATORS WHERE REGNUM = 10)),
((SELECT $node_id FROM FILMS WHERE FILMNUM = 7), (SELECT $node_id FROM CREATORS WHERE REGNUM = 8)),
((SELECT $node_id FROM FILMS WHERE FILMNUM = 3), (SELECT $node_id FROM CREATORS WHERE REGNUM = 1));
CREATE TABLE actorKnowsCreator AS EDGE
INSERT INTO actorKnowsCreator  
VALUES 
((SELECT $node_id FROM ACTORS WHERE TABNUM = 1), (SELECT $node_id FROM CREATORS WHERE REGNUM = 2)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 1), (SELECT $node_id FROM CREATORS WHERE REGNUM = 3)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 1), (SELECT $node_id FROM CREATORS WHERE REGNUM = 4)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 2), (SELECT $node_id FROM CREATORS WHERE REGNUM = 5)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 3), (SELECT $node_id FROM CREATORS WHERE REGNUM = 2)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 5), (SELECT $node_id FROM CREATORS WHERE REGNUM = 6)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 8), (SELECT $node_id FROM CREATORS WHERE REGNUM = 3)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 9), (SELECT $node_id FROM CREATORS WHERE REGNUM = 4)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 2), (SELECT $node_id FROM CREATORS WHERE REGNUM = 7)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 8), (SELECT $node_id FROM CREATORS WHERE REGNUM = 5)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 10), (SELECT $node_id FROM CREATORS WHERE REGNUM = 10)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 7), (SELECT $node_id FROM CREATORS WHERE REGNUM = 8)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 3), (SELECT $node_id FROM CREATORS WHERE REGNUM = 1));
CREATE TABLE actorKnowsActor AS EDGE
INSERT INTO actorKnowsActor  
VALUES 
((SELECT $node_id FROM ACTORS WHERE TABNUM = 1), (SELECT $node_id FROM ACTORS WHERE TABNUM = 2)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 1), (SELECT $node_id FROM ACTORS WHERE TABNUM = 3)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 1), (SELECT $node_id FROM ACTORS WHERE TABNUM = 4)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 2), (SELECT $node_id FROM ACTORS WHERE TABNUM = 5)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 3), (SELECT $node_id FROM ACTORS WHERE TABNUM = 2)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 5), (SELECT $node_id FROM ACTORS WHERE TABNUM = 6)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 8), (SELECT $node_id FROM ACTORS WHERE TABNUM = 3)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 9), (SELECT $node_id FROM ACTORS WHERE TABNUM = 4)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 2), (SELECT $node_id FROM ACTORS WHERE TABNUM = 7)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 8), (SELECT $node_id FROM ACTORS WHERE TABNUM = 5)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 10), (SELECT $node_id FROM ACTORS WHERE TABNUM = 10)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 7), (SELECT $node_id FROM ACTORS WHERE TABNUM = 8)),
((SELECT $node_id FROM ACTORS WHERE TABNUM = 3), (SELECT $node_id FROM ACTORS WHERE TABNUM = 1));

SELECT
a.ACTNAME, a.AGE, c.CREATNAME, c.AGE
FROM
    ACTORS a, CREATORS c, actorKnowsCreator aKC
WHERE
    MATCH(a-(aKC)->c)
and a.ACTNAME='Leonardo DiCaprio'

SELECT
a.ACTNAME, a.AGE, c.CREATNAME, c.AGE
FROM
    ACTORS a, CREATORS c, actorKnowsCreator aKC
WHERE
    MATCH(a-(aKC)->c)
and a.ACTNAME!='Leonardo DiCaprio'


SELECT
a.ACTNAME, a.AGE, c.CREATNAME, c.AGE
FROM
    ACTORS a, CREATORS c, actorKnowsCreator aKC
WHERE
    MATCH(a-(aKC)->c)
and c.CREATNAME='Francis Ford Coppola'

SELECT
a.ACTNAME, a.AGE, c.CREATNAME, c.AGE, f.FILMNAME, f.FYEAR
FROM
    ACTORS a, CREATORS c, actorKnowsCreator aKC, filmByCreator fBC, FILMS f
WHERE
    MATCH(a-(aKC)->c<-(fBC)-f)
and f.FILMNAME!='Inception'


SELECT
a.ACTNAME, a.AGE,  f.FILMNAME, f.FYEAR
FROM
    ACTORS a, actorInFilm aIF,  FILMS f
WHERE
    MATCH(a-(aIF)->f)
and f.FILMNAME='Inception'

SELECT ActorName, Links
FROM (
    SELECT
        actor1.ACTNAME AS ActorName,
        STRING_AGG(actor2.ACTNAME, '->') WITHIN GROUP (GRAPH PATH) AS Links,
        LAST_VALUE(actor2.ACTNAME) WITHIN GROUP (GRAPH PATH) AS LastNode
    FROM
        ACTORS AS actor1,
        actorKnowsActor FOR PATH AS aKA,
        ACTORS FOR PATH AS actor2
    WHERE MATCH(SHORTEST_PATH(actor1(-(aKA)->actor2)+))
    AND actor1.ACTNAME = 'Leonardo DiCaprio'
) AS Q
WHERE Q.LastNode != 'Leonardo DiCaprio'

SELECT ActorName, Links
FROM (
    SELECT
        actor1.ACTNAME AS ActorName,
        STRING_AGG(actor2.ACTNAME, '->') WITHIN GROUP (GRAPH PATH) AS Links,
        LAST_VALUE(actor2.ACTNAME) WITHIN GROUP (GRAPH PATH) AS LastNode
    FROM
        ACTORS AS actor1,
        actorKnowsActor FOR PATH AS aKA,
        ACTORS FOR PATH AS actor2
    WHERE MATCH(SHORTEST_PATH(actor1(-(aKA)->actor2)+))
    AND actor1.ACTNAME = 'Marlon Brando'
) AS Q
WHERE Q.LastNode = 'Marlon Brando'

SELECT ActorName, Links
FROM (
    SELECT
        actor1.ACTNAME AS ActorName,
        STRING_AGG(actor2.ACTNAME, '->') WITHIN GROUP (GRAPH PATH) AS Links,
        LAST_VALUE(actor2.ACTNAME) WITHIN GROUP (GRAPH PATH) AS LastNode
    FROM
        ACTORS AS actor1,
        actorKnowsActor FOR PATH AS aKA,
        ACTORS FOR PATH AS actor2
    WHERE MATCH(SHORTEST_PATH(actor1(-(aKA)->actor2){1,3}))
    AND actor1.ACTNAME = 'Marlon Brando'
) AS Q
WHERE Q.LastNode = 'Marlon Brando'